# Generated by Django 3.1.1 on 2020-10-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
