# Generated by Django 3.1.1 on 2020-10-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201019_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='course2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='course3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='course4',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
