# Generated by Django 3.1.1 on 2020-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201022_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_6',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
