# Generated by Django 3.1.1 on 2020-10-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201022_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_1',
            field=models.CharField(max_length=50),
        ),
    ]
