# Generated by Django 3.1.2 on 2020-11-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201030_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course_5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course_6',
        ),
    ]
