# Generated by Django 3.1.2 on 2020-10-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4)),
                ('catalog_number', models.CharField(max_length=4)),
                ('class_section', models.CharField(max_length=3)),
                ('class_number', models.IntegerField()),
                ('class_title', models.CharField(max_length=100)),
                ('class_topic_formal_desc', models.CharField(max_length=500)),
                ('instructor', models.CharField(max_length=50)),
                ('enrollment_capacity', models.PositiveSmallIntegerField()),
                ('meeting_days', models.CharField(max_length=5)),
                ('meeting_time_start', models.CharField(max_length=10)),
                ('meeting_time_end', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=10)),
                ('term_desc', models.CharField(max_length=15)),
            ],
        ),
    ]
