# Generated by Django 3.1.2 on 2020-10-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_section',
            field=models.CharField(max_length=4),
        ),
    ]
