# Generated by Django 3.1.1 on 2020-11-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_studentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='subject',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
