# Generated by Django 3.1.1 on 2020-11-22 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_auto_20201102_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=4, verbose_name='Catalog Number (ex. 2150)'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='difficulty',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Difficulty from 1 (easy) to 10 (hard)'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='subject',
            field=models.CharField(blank=True, max_length=4, verbose_name='Subject (ex. CS)'),
        ),
    ]
