# Generated by Django 3.1.1 on 2020-11-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_auto_20201102_2102'),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='social_app.studentcourse'),
        ),
    ]
