# Generated by Django 3.1.1 on 2020-11-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='meeting_url',
            field=models.URLField(default='https://meet.google.com/'),
        ),
    ]
